### PR TITLE
upload problem 1560C

### PR DESCRIPTION
**Pull request by Shubhambawner**
## Related Issue

-   Info about the related issue:
source code  upload

Closes: #39  

### description of changes made:

Source code of problem: 1560C from codeforces uploaded
(this was soved by me on the platform as a part of contest, so please specify if I am required to make some changes or updates) 
the code was compiled and passed all test cases as can be seen at: 
https://codeforces.com/submissions/wurtzreaxnwittigreaxn
(please note that wurtzreaxnwittigreaxn is my codeforces handle)

All the corrections/sessions are welcome 

## Programming language

-   [ ] C
-   [x] C++
-   [ ] Java
-   [ ] Python
-   [ ] Javascript

### CODE REVIEW

**Comment by Shubhambawner** [comment]
is it OK if i submit multiple prs sumultaneously ?

**Comment by deephunt3r** [comment]
@Shubhambawner It's good!

**Comment by tireless-22** [comment]
change the .txt to .cpp

**Comment by tireless-22** [comment]
Your code is not correct

**Comment by Shubhambawner** [comment]
I am really sorry for the delay, And thanks @deephunt3r  for re-opening the pr  :)
Here I am attaching the screen shot of codeforces judgement on this code;
please make sure that the code is being checked for problem 1560C on codeforces, and C++(14 or higher) GNU C++ 17

1560C

direct link to the same is:
https://codeforces.com/contest/1560/submission/129906325


while I see no difference in these two codes, please kindly convey what exact error is being incured @tireless-22
1560Csecond

**Comment by deephunt3r** [comment]
@tireless-22 can you please review once again!

**Comment by tireless-22** [comment]
I checked the code again, there is no mistake in this code

**Review by deephunt3r — APPROVED** [review]

**Pull request merged**
