### PR TITLE
Create Mutations.py

### PR DESCRIPTION
**Pull request by SURYACODER**
## Related Issue
[Link For the Problem](https://www.hackerrank.com/challenges/python-mutations/problem)
-   Mutations of Python.

Closes: #24 

## Programming language

-   [ ] C
-   [ ] C++
-   [ ] Java
-   [X] Python
-   [ ] Javascript

### CODE REVIEW

**Comment by tireless-22** [comment]
Hey, @SURYACODER don't make PR directly . We have to check whether the problem is already there or not .After that we will assign you to solve this issue

**Comment by tireless-22** [comment]
hackerearth
peoblem name folder(create one)

**Comment by SURYACODER** [comment]
> Hey, @SURYACODER don't make PR directly . We have to check whether the problem is already there or not .After that we will assign you to solve this issue

Ok plz assign me this issue I will create a new PR by creating a new folder.

**Comment by tireless-22** [comment]
I already assigned you for that

**Comment by deephunt3r** [comment]
Okay! Create new PR
Thanks!

**Pull request closed without merging**
