### PR TITLE
FLOOD FILL ALGO IN CPP

### PR DESCRIPTION
**Pull request by 2SkeePeR2**
## Related Issue 

Adds solution to flood fill problem on leetcode in CPP 

Closes: #13

### Describe the changes you've made

- Add a solution for flood fill algorithim in leetcode folder

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Language used
- [ ] C
- [x] CPP
- [ ] Python
- [ ] Java

### CODE REVIEW

**Review by tireless-22 — APPROVED** [review]

**Comment by 2SkeePeR2** [comment]
Will you guys merge the PR?

**Comment by deephunt3r** [comment]
@2SkeePeR2 could you please add problem link at top of the file with in comments

**Comment by deephunt3r** [comment]
> Will you guys merge the PR?

Yeah! We will merge it if you made required changes

**Review by deephunt3r — APPROVED** [review]
LGTM! Thanks for your contribution 🚀

**Comment by 2SkeePeR2** [comment]
@deephunt3r can you add the ```hacktoberfest-accepted``` tag?

**Comment by deephunt3r** [comment]
> @deephunt3r can you add the `hacktoberfest-accepted` tag?

Sorry! I'll add it

**Pull request merged**
